### ISSUE TITLE
Error in the Query field - Field must contain valid SQL to be run against osquery tables

### ISSUE THREAD

**Issue by rubenrodr-versia** [mwielgoszewski/doorman#122]
Hi,

We have windows machines with osqueryd installed pointing to doorman with the flags to be able to read the windows events:

`--disable_events=false`
`--windows_event_channels='System,Application,Setup,Security'`

When we try to create a query for the windows_events table we get this error:

![image](https://user-images.githubusercontent.com/24841626/29807362-ea2cb9e4-8c93-11e7-82a0-f5c2bc94eb96.png)

Thanks.
Best regards.

**Comment by mwielgoszewski** [comment]
Hey @rubenrodr-versia - we haven't updated the osquery schema we used to validate queries against in a while, but will shortly. I'll update this ticket once that's done and you can fetch a new release.

In the mean time, you can update the `DOORMAN_EXTRA_SCHEMA` configuration value with the following (and restart the Doorman app):

```
DOORMAN_EXTRA_SCHEMA = [
  'CREATE TABLE windows_events (time BIGINT, datetime TEXT, source TEXT, provider_name TEXT, provider_guid TEXT, eventid INTEGER, task INTEGER, level INTEGER, keywords BIGINT, data TEXT, eid TEXT);'
]
```

For context, we create an in-memory sqlite database to validate that queries will execute successfully. This database (because the schema hasn't been updated in a while), doesn't include the `windows_events` table, which can be overridden by updating the `DOORMAN_EXTRA_SCHEMA` configuration parameter.
