### ISSUE TITLE
Unable to upload packs

### ISSUE THREAD

**Issue by rubenrodr-versia** [mwielgoszewski/doorman#126]
Hi Marcin,

When i try to upload a pack i get the message:

![image](https://user-images.githubusercontent.com/24841626/29861165-a45dbc08-8d68-11e7-81ca-ac82b4216078.png)

but doorman is not displaying any pack after this.

Thanks.
Best regards.

**Comment by rubenrodr-versia** [comment]
I noticed that when adding a new query, packs are being displayed:

![image](https://user-images.githubusercontent.com/24841626/29870708-2fb50318-8d89-11e7-96c6-2b8331b5d049.png)

**Comment by mwielgoszewski** [comment]
I introduced a bug in some query refactoring I did. In an attempt to improve query performance by replacing `LEFT OUTER JOIN`s with `INNER JOIN`'s I neglected to account for the fact that that would exclude packs that contain queries with no tags on both the packs view and queries view pages.

Fixed in 7cb4abd.
